sudo: required 
dist: xenial 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
    - ROS_DISTRO=kinetic
  matrix:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="melodic" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
    - env: ROS_DISTRO="melodic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - source .ci_config/travis.sh
